theme: jekyll-theme-cayman
title: Revisiting Binary Local Image Description for Resource Limited Devices
description: Iago Suárez, José M. Buenaposada, Luis Baumela  
arxiv: https://arxiv.org/pdf/2108.08380.pdf
doi: https://doi.org/10.1109/LRA.2021.3107024

twitter_username: IagoSuarez0
github_username:  iago-suarez